#!/usr/bin/env bash
# a Bash script that installs nginx on our web-01 server
sudo apt-get update -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx restart
